# -*- coding: utf-8 -*-
"""Assignment-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TnMy-3D0PKhYiOjdZeYLjml5p-SBKidF
"""

import numpy as np
import os
def Split_file(url,n=10):
  climate_data=np.genfromtxt(url,delimiter=',',skip_header=1)
  splited_arr=np.array_split(climate_data,n)
  if 'climate_project' in os.listdir():
                   pass
  else:
      os.mkdir('climate_project')
  for i in range(n):
      np.savetxt(f'climate_project/climate_data_team{i}.csv',splited_arr[i],delimiter=',',fmt='%i',header='temperature,rainfall,humidity')
  return (os.listdir('/content/climate_project'))
file_url='https://raw.githubusercontent.com/svkarthik86/Advanced-python/main/climate.txt'
Split_file(file_url, n=10)